implement suggestions from joss reviewer
scikit-tda/DREiMac pull request #13
Opened 2023-10-17 10:41 UTC by LuisScoccola

- leading underscore convention for private attributes
- delete unused type attributes
- untrack notebook not used in documentation
- small style improvements
- <3.12 constraint to python version due to numba compatibility

2023-10-19 20:14 UTC, raphaelreinauer requested changes
LGTM. Please remove the outputs in the juyper notebook from git.

2023-10-19 20:14 UTC, raphaelreinauer commented on docs/notebooks/bullseye.ipynb
Outputs shouldn't be committed to git. It's otherwise very hard to see if the code changed ore only the outputs.

2023-10-19 20:28 UTC, LuisScoccola commented on docs/notebooks/bullseye.ipynb
Thank you for the feedback. The reason for having the outputs in the notebooks is that we are using the notebooks as documentation, so we want to have the user be able to see the output without necessarily running the notebooks. But this is most relevant for the documentation itself, which just includes the notebooks and thus requires the outputs to be there. Do you know if it is possible to have the notebooks without output in the repository, and have the documentation CI action run each cell of each notebook before compiling the documentation and putting it online?

2023-10-20 08:45 UTC, raphaelreinauer commented on docs/notebooks/bullseye.ipynb
This might be helpful:
https://mg.readthedocs.io/git-jupyter.html

2023-10-20 11:02 UTC, ctralie commented
Thanks for the input here.
This doesn't quite address our workflow with the documentation, so I'd like
to request that we move on from this and leave it be.
Thanks,
Chris

On Fri, Oct 20, 2023 at 4:46 AM raphaelreinauer ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On docs/notebooks/bullseye.ipynb
> <https://github.com/scikit-tda/DREiMac/pull/13#discussion_r1366672190>:
>
> This might be helpful:
> https://mg.readthedocs.io/git-jupyter.html
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/scikit-tda/DREiMac/pull/13#discussion_r1366672190>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJWDZW2JM5ZNUCS6RC3ZTLYAI24JAVCNFSM6AAAAAA6DTZHKGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMOBZGU2DSMBXGE>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-10-20 11:06 UTC, ctralie commented on docs/notebooks/bullseye.ipynb
Thanks for the input here.
This doesn't quite address our workflow with the documentation, so I'd like
to request that we move on from this and leave it be for now.
Thanks,
Chris

2023-10-20 11:30 UTC, raphaelreinauer commented on docs/notebooks/bullseye.ipynb
@ctralie, I understand your perspective. However, for PR reviews, navigating through binaries takes work. Perhaps something like [ReviewNB](https://www.reviewnb.com/) could be a solution? Just a thought.

2023-10-20 11:51 UTC, ctralie commented on docs/notebooks/bullseye.ipynb
Thanks for the quick response.  I'm curious why you'd look at the binaries directly though.  Why not just look at the notebooks themselves, since github renders them?

2023-10-20 12:20 UTC, ctralie commented on docs/notebooks/bullseye.ipynb
(This tool does look nice though @raphaelreinauer.  I'm just wondering if, in the interest of time, and in the interest of keeping the toolchain simpler, we can punt this issue for now)

2023-10-20 14:59 UTC, raphaelreinauer commented on docs/notebooks/bullseye.ipynb
This is purely a personal preference (see the Review channel), so please consider it a suggestion to add in the future.

Reviewing a PR, I look at change logs to determine the modifications. The diff in the Jupyter Notebook has both code changes and binaries. However, the binary changes can often overshadow the code modifications, making the PR challenging to review.

2023-10-20 15:00 UTC, raphaelreinauer approved these changes

2023-10-20 15:08 UTC, raphaelreinauer commented on docs/notebooks/bullseye.ipynb
Another drawback of committing binaries (which could even change often like plots in Jupyter Notebooks) is that the repository size increases significantly as these files remain in the git history.

2023-10-20 17:07 UTC, ctralie commented on docs/notebooks/bullseye.ipynb
Yes, understood, and agreed that it is a pain.  I do wish that matplotlib saved svgs instead of pngs where possible in notebooks.  But thank you for your flexibility here

2023-11-15 12:10 UTC, merged